#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import yaml


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = REPOSITORY_ROOT / "skills"
CATEGORIES_PATH = REPOSITORY_ROOT / "design" / "skill-categories.yaml"
OUTPUT_PATH = REPOSITORY_ROOT / "design" / "generated" / "skill-definitions.js"
ROLE_SCHEMA_PATH = REPOSITORY_ROOT / "agents" / "role-schema.yaml"
ROLES_ROOT = REPOSITORY_ROOT / "agents" / "roles"
ROLE_OUTPUT_PATH = REPOSITORY_ROOT / "design" / "generated" / "role-definitions.js"
GENERATED_ADAPTERS_ROOT = REPOSITORY_ROOT / "generated" / "adapters"
CODEX_AGENT_OUTPUT_ROOT = GENERATED_ADAPTERS_ROOT / "codex" / "agents"
CLAUDE_AGENT_OUTPUT_ROOT = GENERATED_ADAPTERS_ROOT / "claude" / "agents"
SKILL_FILE_NAME = "SKILL.md"
AGENTS_FOLDER_NAME = "agents"
OPENAI_METADATA_FILE_NAME = "openai.yaml"
FRONTMATTER_DELIMITER = "---"
METADATA_SECTION_KEY = "metadata"
CATEGORY_FIELD_NAME = "category"
CATEGORIES_FIELD_NAME = "categories"
CATEGORY_ID_FIELD_NAME = "id"
CATEGORY_LABEL_FIELD_NAME = "label"
INTERFACE_SECTION_KEY = "interface"
DISPLAY_NAME_FIELD_NAME = "display_name"
SHORT_DESCRIPTION_FIELD_NAME = "short_description"
NAME_FIELD_NAME = "name"
DESCRIPTION_FIELD_NAME = "description"
CODE_FENCE_MARKER = "```"
HEADING_LEVEL_OFFSET = 1
MAX_HEADING_LEVEL = 6
EMPTY_INDEX = 0
NEXT_INDEX = 1
SUCCESS_EXIT_CODE = 0
ERROR_EXIT_CODE = 1
GENERATOR_RELATIVE_PATH = "scripts/build-skill-docs.py"
OUTPUT_GLOBAL_NAME = "DEV_METHODOLOGY_SKILL_DEFINITIONS"
ROLE_OUTPUT_GLOBAL_NAME = "DEV_METHODOLOGY_ROLE_DEFINITIONS"
ROLE_FILE_SUFFIX = ".role.yaml"
ROLE_SCHEMA_REQUIRED_KEY = "required"
ROLE_SCHEMA_PROPERTIES_KEY = "properties"
ROLE_SCHEMA_GROUPS_KEY = "roleGroups"
ROLE_NAME_FIELD_NAME = "name"
ROLE_FILENAME_FIELD_NAME = "filename"
ROLE_DESCRIPTION_FIELD_NAME = "description"
ROLE_INSTRUCTIONS_FIELD_NAME = "instructions"
ROLE_SKILLS_FIELD_NAME = "skills"
ROLE_OUTPUT_CONTRACT_FIELD_NAME = "outputContract"
ROLE_SKILL_COMMENTS_FIELD_NAME = "skillComments"
ROLE_OUTPUT_COMMENTS_FIELD_NAME = "outputComments"
ROLE_EXAMPLES_FIELD_NAME = "examples"
ROLE_EXAMPLE_RUNTIME_INVOCATIONS_FIELD_NAME = "runtimeInvocations"
ROLE_EXAMPLE_REQUIRED_FIELDS = (
    "purpose",
    ROLE_EXAMPLE_RUNTIME_INVOCATIONS_FIELD_NAME,
    "plausibleResponse",
)
ROLE_EXAMPLE_RUNTIME_IDS = ("codex", "claude-code")
ROLE_LIST_FIELDS = (
    ROLE_SKILLS_FIELD_NAME,
    "tools",
    "disallowedTools",
    "mcpServers",
    ROLE_OUTPUT_CONTRACT_FIELD_NAME,
)
ROLE_STRING_FIELDS = (
    ROLE_NAME_FIELD_NAME,
    ROLE_FILENAME_FIELD_NAME,
    ROLE_DESCRIPTION_FIELD_NAME,
    ROLE_INSTRUCTIONS_FIELD_NAME,
    "model",
    "effort",
    "permissionMode",
    "isolation",
    "memory",
)
ROLE_INTEGER_FIELDS = ("maxTurns", "timeout")
ROLE_GROUP_LABELS = {
    "methodology-maintenance": "Methodology Maintenance Agents",
    "project-setup": "Project Setup And Update Agents",
    "development-use": "Development Use Agents",
}
CODEX_ADAPTER_NAME = "codex"
CLAUDE_ADAPTER_NAME = "claude"
CODEX_AGENT_EXTENSION = ".toml"
CLAUDE_AGENT_EXTENSION = ".md"
CODEX_REASONING_FIELD_NAME = "model_reasoning_effort"
CODEX_SANDBOX_FIELD_NAME = "sandbox_mode"
CODEX_READ_ONLY_ISOLATION = "read-only"
TOML_MULTILINE_BASIC_STRING_DELIMITER = '"""'
GENERATED_FILE_HEADER = "Generated by scripts/build-skill-docs.py. Do not edit by hand."
ROLE_SKILL_INSTRUCTION_PREFIX = "Load these skills when applicable:"
ROLE_OUTPUT_INSTRUCTION_PREFIX = "Return:"
ROLE_DISPLAY_ACRONYMS = {"e2e": "E2E", "qa": "QA", "ux": "UX"}
MINIMUM_POSITIVE_INTEGER = 1
CATEGORY_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]*$")
HEADING_PATTERN = re.compile(r"^(#{1,6})\s+(.*)$")
BULLET_PATTERN = re.compile(r"^\s*-\s+(.*)$")
ORDERED_PATTERN = re.compile(r"^\s*\d+\.\s+(.*)$")
MARKDOWN_LINK_PATTERN = re.compile(r"\[([^\]]+)]\(([^)]+)\)")
STRONG_PATTERN = re.compile(r"\*\*([^*]+)\*\*")
EMPHASIS_PATTERN = re.compile(r"\*([^*]+)\*")


@dataclass(frozen=True)
class Category:
    id: str
    label: str


@dataclass(frozen=True)
class SkillDefinition:
    name: str
    display_name: str
    description: str
    short_description: str
    category: str
    category_label: str
    source_path: str
    markdown: str
    html: str


@dataclass(frozen=True)
class RoleDefinition:
    name: str
    filename: str
    display_name: str
    description: str
    instructions: str
    skills: tuple[str, ...]
    skill_comments: dict[str, str]
    output_contract: tuple[str, ...]
    output_comments: dict[str, str]
    examples: tuple[dict[str, object], ...]
    group: str
    group_label: str
    source_path: str
    yaml: str
    optional_fields: dict[str, object]


def split_frontmatter(text: str, source_path: Path) -> tuple[dict[str, object], str]:
    lines = text.splitlines()
    if not lines or lines[EMPTY_INDEX] != FRONTMATTER_DELIMITER:
        raise ValueError(f"Missing YAML frontmatter: {source_path}")

    for index, line in enumerate(lines[NEXT_INDEX:], start=NEXT_INDEX):
        if line == FRONTMATTER_DELIMITER:
            frontmatter = yaml.safe_load("\n".join(lines[NEXT_INDEX:index]))
            if not isinstance(frontmatter, dict):
                raise ValueError(f"Frontmatter must be a YAML object: {source_path}")
            return frontmatter, "\n".join(lines[index + NEXT_INDEX :]).lstrip()

    raise ValueError(f"Missing closing frontmatter delimiter: {source_path}")


def read_yaml_object(path: Path) -> dict[str, object]:
    parsed = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(parsed, dict):
        raise ValueError(f"YAML file must contain an object: {path}")
    return parsed


def load_categories() -> list[Category]:
    parsed = read_yaml_object(CATEGORIES_PATH)
    category_items = parsed.get(CATEGORIES_FIELD_NAME)
    if not isinstance(category_items, list):
        raise ValueError("skill-categories.yaml must define a categories list.")

    categories: list[Category] = []
    seen_ids: set[str] = set()
    for item in category_items:
        if not isinstance(item, dict):
            raise ValueError("Each category must be an object.")
        category_id = item.get(CATEGORY_ID_FIELD_NAME)
        label = item.get(CATEGORY_LABEL_FIELD_NAME)
        if not isinstance(category_id, str) or not CATEGORY_PATTERN.fullmatch(category_id):
            raise ValueError(f"Invalid category id: {category_id}")
        if category_id in seen_ids:
            raise ValueError(f"Duplicate category id: {category_id}")
        if not isinstance(label, str) or not label.strip():
            raise ValueError(f"Missing category label for {category_id}")
        categories.append(Category(category_id, label.strip()))
        seen_ids.add(category_id)

    return categories


def category_from_frontmatter(frontmatter: dict[str, object], source_path: Path) -> str:
    metadata = frontmatter.get(METADATA_SECTION_KEY)
    if not isinstance(metadata, dict):
        raise ValueError(f"Skill metadata must define category: {source_path}")
    category = metadata.get(CATEGORY_FIELD_NAME)
    if not isinstance(category, str) or not category.strip():
        raise ValueError(f"Skill metadata category is missing: {source_path}")
    if not CATEGORY_PATTERN.fullmatch(category):
        raise ValueError(f"Skill metadata category is invalid: {source_path}")
    return category


def load_openai_interface(skill_directory: Path) -> dict[str, object]:
    metadata_path = skill_directory / AGENTS_FOLDER_NAME / OPENAI_METADATA_FILE_NAME
    if not metadata_path.is_file():
        return {}
    parsed = read_yaml_object(metadata_path)
    interface = parsed.get(INTERFACE_SECTION_KEY)
    return interface if isinstance(interface, dict) else {}


def display_name_from_skill_name(skill_name: str) -> str:
    return re.sub(r"[-_]+", " ", skill_name).title()


def first_sentence(description: str) -> str:
    return re.split(r"(?<=[.!?])\s+", description.strip(), maxsplit=NEXT_INDEX)[EMPTY_INDEX]


def format_inline(text: str) -> str:
    escaped = html.escape(text, quote=True)

    def replace_link(match: re.Match[str]) -> str:
        label = html.escape(match.group(NEXT_INDEX), quote=True)
        href = html.escape(match.group(2), quote=True)
        return f'<a href="{href}">{label}</a>'

    escaped = MARKDOWN_LINK_PATTERN.sub(replace_link, escaped)
    escaped = STRONG_PATTERN.sub(r"<strong>\1</strong>", escaped)
    return EMPHASIS_PATTERN.sub(r"<em>\1</em>", escaped)


def render_markdown(markdown: str) -> str:
    lines = markdown.splitlines()
    parts: list[str] = []
    paragraph_lines: list[str] = []
    list_items: list[str] = []
    list_tag = ""
    code_lines: list[str] = []
    in_code_block = False

    def close_paragraph() -> None:
        if paragraph_lines:
            parts.append(f"<p>{format_inline(' '.join(paragraph_lines))}</p>")
            paragraph_lines.clear()

    def close_list() -> None:
        nonlocal list_tag
        if list_items:
            parts.append(f"<{list_tag}>{''.join(list_items)}</{list_tag}>")
            list_items.clear()
            list_tag = ""

    def close_code_block() -> None:
        nonlocal in_code_block
        parts.append(f"<pre><code>{html.escape(chr(10).join(code_lines))}</code></pre>")
        code_lines.clear()
        in_code_block = False

    for line in lines:
        trimmed = line.strip()
        if trimmed.startswith(CODE_FENCE_MARKER):
            if in_code_block:
                close_code_block()
            else:
                close_paragraph()
                close_list()
                in_code_block = True
            continue

        if in_code_block:
            code_lines.append(line)
            continue

        if not trimmed:
            close_paragraph()
            close_list()
            continue

        heading_match = HEADING_PATTERN.match(trimmed)
        if heading_match:
            close_paragraph()
            close_list()
            heading_level = min(len(heading_match.group(NEXT_INDEX)) + HEADING_LEVEL_OFFSET, MAX_HEADING_LEVEL)
            parts.append(f"<h{heading_level}>{format_inline(heading_match.group(2))}</h{heading_level}>")
            continue

        bullet_match = BULLET_PATTERN.match(line)
        if bullet_match:
            close_paragraph()
            if list_tag and list_tag != "ul":
                close_list()
            list_tag = "ul"
            list_items.append(f"<li>{format_inline(bullet_match.group(NEXT_INDEX))}</li>")
            continue

        ordered_match = ORDERED_PATTERN.match(line)
        if ordered_match:
            close_paragraph()
            if list_tag and list_tag != "ol":
                close_list()
            list_tag = "ol"
            list_items.append(f"<li>{format_inline(ordered_match.group(NEXT_INDEX))}</li>")
            continue

        close_list()
        paragraph_lines.append(trimmed)

    if in_code_block:
        close_code_block()
    close_paragraph()
    close_list()
    return "\n".join(parts)


def load_skill_definition(skill_directory: Path, categories_by_id: dict[str, Category]) -> SkillDefinition:
    skill_path = skill_directory / SKILL_FILE_NAME
    raw_markdown = skill_path.read_text(encoding="utf-8")
    frontmatter, body_markdown = split_frontmatter(raw_markdown, skill_path)
    name = frontmatter.get(NAME_FIELD_NAME)
    description = frontmatter.get(DESCRIPTION_FIELD_NAME)
    if not isinstance(name, str) or not isinstance(description, str):
        raise ValueError(f"Skill frontmatter must define name and description: {skill_path}")

    category_id = category_from_frontmatter(frontmatter, skill_path)
    category = categories_by_id.get(category_id)
    if category is None:
        raise ValueError(f"Unknown category {category_id}: {skill_path}")

    interface = load_openai_interface(skill_directory)
    display_name = interface.get(DISPLAY_NAME_FIELD_NAME)
    short_description = interface.get(SHORT_DESCRIPTION_FIELD_NAME)
    return SkillDefinition(
        name=name,
        display_name=display_name if isinstance(display_name, str) else display_name_from_skill_name(name),
        description=description.strip(),
        short_description=short_description if isinstance(short_description, str) else first_sentence(description),
        category=category.id,
        category_label=category.label,
        source_path=str(skill_path.relative_to(REPOSITORY_ROOT)),
        markdown=raw_markdown,
        html=render_markdown(body_markdown),
    )


def skill_directories() -> list[Path]:
    return sorted(path.parent for path in SKILLS_ROOT.glob(f"*/{SKILL_FILE_NAME}"))


def role_display_name(role_name: str) -> str:
    words = []
    for word in role_name.split("-"):
        words.append(ROLE_DISPLAY_ACRONYMS.get(word, word.title()))
    return " ".join(words)


def validate_string_list(value: object, field_name: str, source_path: Path) -> tuple[str, ...]:
    if not isinstance(value, list) or not value:
        raise ValueError(f"Role {field_name} must be a non-empty list: {source_path}")
    if any(not isinstance(item, str) or not item.strip() for item in value):
        raise ValueError(f"Role {field_name} must contain non-empty strings: {source_path}")
    normalized = tuple(item.strip() for item in value)
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"Role {field_name} contains duplicates: {source_path}")
    return normalized


def validate_role_examples(value: object, source_path: Path) -> tuple[dict[str, object], ...]:
    if not isinstance(value, list) or not value:
        raise ValueError(f"Role {ROLE_EXAMPLES_FIELD_NAME} must be a non-empty list: {source_path}")

    examples: list[dict[str, object]] = []
    for index, example in enumerate(value, start=MINIMUM_POSITIVE_INTEGER):
        if not isinstance(example, dict):
            raise ValueError(f"Role example {index} must be an object: {source_path}")
        unknown_fields = sorted(set(example) - set(ROLE_EXAMPLE_REQUIRED_FIELDS))
        missing_fields = sorted(set(ROLE_EXAMPLE_REQUIRED_FIELDS) - set(example))
        if unknown_fields or missing_fields:
            raise ValueError(
                f"Role example {index} must contain only {ROLE_EXAMPLE_REQUIRED_FIELDS}: {source_path}"
            )
        normalized: dict[str, object] = {}
        for field_name in ROLE_EXAMPLE_REQUIRED_FIELDS:
            field_value = example[field_name]
            if field_name == ROLE_EXAMPLE_RUNTIME_INVOCATIONS_FIELD_NAME:
                if not isinstance(field_value, dict) or set(field_value) != set(ROLE_EXAMPLE_RUNTIME_IDS):
                    raise ValueError(
                        f"Role example {index} {field_name} keys must match {ROLE_EXAMPLE_RUNTIME_IDS}: {source_path}"
                    )
                invocations: dict[str, str] = {}
                for runtime_id in ROLE_EXAMPLE_RUNTIME_IDS:
                    invocation = field_value[runtime_id]
                    if not isinstance(invocation, str) or not invocation.strip():
                        raise ValueError(
                            f"Role example {index} {field_name} {runtime_id} must be a non-empty string: {source_path}"
                        )
                    invocations[runtime_id] = invocation.strip()
                normalized[field_name] = invocations
                continue
            if not isinstance(field_value, str) or not field_value.strip():
                raise ValueError(
                    f"Role example {index} {field_name} must be a non-empty string: {source_path}"
                )
            normalized[field_name] = field_value.strip()
        examples.append(normalized)

    return tuple(examples)


def validate_comment_map(
    value: object,
    field_name: str,
    expected_keys: tuple[str, ...],
    source_path: Path,
) -> dict[str, str]:
    if not isinstance(value, dict):
        raise ValueError(f"Role {field_name} must be a mapping: {source_path}")
    if set(value) != set(expected_keys):
        raise ValueError(
            f"Role {field_name} keys must match {expected_keys}: {source_path}"
        )
    comments: dict[str, str] = {}
    for key in expected_keys:
        comment = value[key]
        if not isinstance(comment, str) or not comment.strip():
            raise ValueError(f"Role {field_name} {key} must be a non-empty string: {source_path}")
        comments[key] = comment.strip()
    return comments


def load_role_schema() -> tuple[set[str], set[str], set[str]]:
    schema = read_yaml_object(ROLE_SCHEMA_PATH)
    required = validate_string_list(
        schema.get(ROLE_SCHEMA_REQUIRED_KEY),
        ROLE_SCHEMA_REQUIRED_KEY,
        ROLE_SCHEMA_PATH,
    )
    properties = schema.get(ROLE_SCHEMA_PROPERTIES_KEY)
    if not isinstance(properties, dict) or not properties:
        raise ValueError("role-schema.yaml must define properties.")
    groups = validate_string_list(
        schema.get(ROLE_SCHEMA_GROUPS_KEY),
        ROLE_SCHEMA_GROUPS_KEY,
        ROLE_SCHEMA_PATH,
    )
    if set(groups) != set(ROLE_GROUP_LABELS):
        raise ValueError("role-schema.yaml role groups must match the generated documentation groups.")
    return set(required), set(properties), set(groups)


def role_source_paths() -> list[Path]:
    return sorted(ROLES_ROOT.glob(f"*/*{ROLE_FILE_SUFFIX}"))


def load_role_definition(
    source_path: Path,
    required_fields: set[str],
    allowed_fields: set[str],
    allowed_groups: set[str],
    skill_names: set[str],
) -> RoleDefinition:
    parsed = read_yaml_object(source_path)
    missing_fields = sorted(required_fields - set(parsed))
    if missing_fields:
        raise ValueError(f"Role is missing required fields {missing_fields}: {source_path}")
    unknown_fields = sorted(set(parsed) - allowed_fields)
    if unknown_fields:
        raise ValueError(f"Role has unknown fields {unknown_fields}: {source_path}")

    for field_name in ROLE_STRING_FIELDS:
        value = parsed.get(field_name)
        if value is not None and (not isinstance(value, str) or not value.strip()):
            raise ValueError(f"Role {field_name} must be a non-empty string: {source_path}")
    for field_name in ROLE_INTEGER_FIELDS:
        value = parsed.get(field_name)
        if value is not None and (
            not isinstance(value, int) or isinstance(value, bool) or value < MINIMUM_POSITIVE_INTEGER
        ):
            raise ValueError(f"Role {field_name} must be a positive integer: {source_path}")

    role_name = parsed[ROLE_NAME_FIELD_NAME]
    filename = parsed[ROLE_FILENAME_FIELD_NAME]
    if not isinstance(role_name, str) or not CATEGORY_PATTERN.fullmatch(role_name):
        raise ValueError(f"Invalid role name: {source_path}")
    if not isinstance(filename, str) or not CATEGORY_PATTERN.fullmatch(filename):
        raise ValueError(f"Invalid role filename: {source_path}")
    expected_filename = source_path.name.removesuffix(ROLE_FILE_SUFFIX)
    if filename != expected_filename:
        raise ValueError(f"Role filename must match its source file: {source_path}")

    group = source_path.parent.name
    if group not in allowed_groups:
        raise ValueError(f"Unknown role group {group}: {source_path}")

    list_values: dict[str, tuple[str, ...]] = {}
    for field_name in ROLE_LIST_FIELDS:
        value = parsed.get(field_name)
        if value is not None:
            list_values[field_name] = validate_string_list(value, field_name, source_path)

    examples = ()
    if ROLE_EXAMPLES_FIELD_NAME in parsed:
        examples = validate_role_examples(parsed[ROLE_EXAMPLES_FIELD_NAME], source_path)

    role_skills = list_values[ROLE_SKILLS_FIELD_NAME]
    unknown_skills = sorted(set(role_skills) - skill_names)
    if unknown_skills:
        raise ValueError(f"Role references unknown skills {unknown_skills}: {source_path}")

    skill_comments = validate_comment_map(
        parsed[ROLE_SKILL_COMMENTS_FIELD_NAME],
        ROLE_SKILL_COMMENTS_FIELD_NAME,
        role_skills,
        source_path,
    )
    output_contract = list_values[ROLE_OUTPUT_CONTRACT_FIELD_NAME]
    output_comments = validate_comment_map(
        parsed[ROLE_OUTPUT_COMMENTS_FIELD_NAME],
        ROLE_OUTPUT_COMMENTS_FIELD_NAME,
        output_contract,
        source_path,
    )

    optional_fields = {
        field_name: parsed[field_name]
        for field_name in sorted(set(parsed) - required_fields - {ROLE_EXAMPLES_FIELD_NAME})
    }
    for field_name, values in list_values.items():
        if field_name in optional_fields:
            optional_fields[field_name] = list(values)

    description = parsed[ROLE_DESCRIPTION_FIELD_NAME]
    instructions = parsed[ROLE_INSTRUCTIONS_FIELD_NAME]
    if not isinstance(description, str) or not isinstance(instructions, str):
        raise ValueError(f"Role description and instructions must be strings: {source_path}")
    return RoleDefinition(
        name=role_name,
        filename=filename,
        display_name=role_display_name(role_name),
        description=description.strip(),
        instructions=instructions.strip(),
        skills=role_skills,
        skill_comments=skill_comments,
        output_contract=output_contract,
        output_comments=output_comments,
        examples=examples,
        group=group,
        group_label=ROLE_GROUP_LABELS[group],
        source_path=str(source_path.relative_to(REPOSITORY_ROOT)),
        yaml=source_path.read_text(encoding="utf-8"),
        optional_fields=optional_fields,
    )


def load_role_definitions(skill_names: set[str]) -> list[RoleDefinition]:
    required_fields, allowed_fields, allowed_groups = load_role_schema()
    roles = [
        load_role_definition(
            source_path,
            required_fields,
            allowed_fields,
            allowed_groups,
            skill_names,
        )
        for source_path in role_source_paths()
    ]
    role_names = [role.name for role in roles]
    filenames = [role.filename for role in roles]
    if len(role_names) != len(set(role_names)):
        raise ValueError("Canonical role names must be unique.")
    if len(filenames) != len(set(filenames)):
        raise ValueError("Canonical role filenames must be unique.")
    return roles


def build_payload() -> dict[str, object]:
    categories = load_categories()
    categories_by_id = {category.id: category for category in categories}
    skills = [load_skill_definition(skill_directory, categories_by_id) for skill_directory in skill_directories()]
    skill_categories = {skill.category for skill in skills}
    missing_categories = sorted(skill_categories - set(categories_by_id))
    if missing_categories:
        raise ValueError("Unknown skill categories: " + ", ".join(missing_categories))

    return {
        "categories": [category.__dict__ for category in categories],
        "skills": {
            skill.name: {
                "name": skill.name,
                "displayName": skill.display_name,
                "description": skill.description,
                "shortDescription": skill.short_description,
                "category": skill.category,
                "categoryLabel": skill.category_label,
                "sourcePath": skill.source_path,
                "markdown": skill.markdown,
                "html": skill.html,
            }
            for skill in skills
        },
    }


def render_javascript(payload: dict[str, object]) -> str:
    serialized = json.dumps(payload, indent=2, sort_keys=True)
    return (
        f"// Generated by {GENERATOR_RELATIVE_PATH}. Do not edit by hand.\n"
        f"window.{OUTPUT_GLOBAL_NAME} = {serialized};\n"
    )


def build_role_payload(roles: Sequence[RoleDefinition]) -> dict[str, object]:
    return {
        "groups": [
            {"id": group_id, "label": group_label}
            for group_id, group_label in ROLE_GROUP_LABELS.items()
        ],
        "roles": {
            role.name: {
                "name": role.name,
                "filename": role.filename,
                "displayName": role.display_name,
                "description": role.description,
                "instructions": role.instructions,
                "skills": list(role.skills),
                "skillComments": role.skill_comments,
                "outputs": list(role.output_contract),
                "outputComments": role.output_comments,
                "examples": list(role.examples),
                "group": role.group,
                "groupLabel": role.group_label,
                "sourcePath": role.source_path,
                "yaml": role.yaml,
                **role.optional_fields,
            }
            for role in roles
        },
    }


def render_role_javascript(roles: Sequence[RoleDefinition]) -> str:
    serialized = json.dumps(build_role_payload(roles), indent=2, sort_keys=True)
    return (
        f"// {GENERATED_FILE_HEADER}\n"
        f"window.{ROLE_OUTPUT_GLOBAL_NAME} = {serialized};\n"
    )


def role_instruction_text(role: RoleDefinition) -> str:
    skill_text = ", ".join(role.skills)
    output_text = "; ".join(role.output_contract)
    return (
        f"{role.instructions}\n\n"
        f"{ROLE_SKILL_INSTRUCTION_PREFIX} {skill_text}.\n\n"
        f"{ROLE_OUTPUT_INSTRUCTION_PREFIX} {output_text}."
    )


def role_adapter_comments(role: RoleDefinition, prefix: str) -> str:
    lines = [f"{prefix}Skill comments:"]
    lines.extend(f"{prefix}- {skill}: {role.skill_comments[skill]}" for skill in role.skills)
    lines.append(f"{prefix}Output comments:")
    lines.extend(
        f"{prefix}- {output}: {role.output_comments[output]}"
        for output in role.output_contract
    )
    return "\n".join(lines)


def render_toml_multiline_basic_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return (
        f"{TOML_MULTILINE_BASIC_STRING_DELIMITER}\n"
        f"{escaped}{TOML_MULTILINE_BASIC_STRING_DELIMITER}"
    )


def render_codex_agent(role: RoleDefinition) -> str:
    fields = [
        f"# {GENERATED_FILE_HEADER}",
        role_adapter_comments(role, "# "),
        f"name = {json.dumps(role.name)}",
        f"description = {json.dumps(role.description)}",
        "developer_instructions = "
        + render_toml_multiline_basic_string(role_instruction_text(role)),
    ]
    model = role.optional_fields.get("model")
    if isinstance(model, str):
        fields.append(f"model = {json.dumps(model)}")
    effort = role.optional_fields.get("effort")
    if isinstance(effort, str):
        fields.append(f"{CODEX_REASONING_FIELD_NAME} = {json.dumps(effort)}")
    isolation = role.optional_fields.get("isolation")
    if isolation == CODEX_READ_ONLY_ISOLATION:
        fields.append(f"{CODEX_SANDBOX_FIELD_NAME} = {json.dumps(isolation)}")
    return "\n".join(fields) + "\n"


def render_claude_agent(role: RoleDefinition) -> str:
    frontmatter: dict[str, object] = {
        ROLE_NAME_FIELD_NAME: role.name,
        ROLE_DESCRIPTION_FIELD_NAME: role.description,
        ROLE_SKILLS_FIELD_NAME: list(role.skills),
    }
    for field_name in (
        "tools",
        "disallowedTools",
        "mcpServers",
        "model",
        "effort",
        "maxTurns",
        "permissionMode",
        "isolation",
        "memory",
    ):
        if field_name in role.optional_fields:
            frontmatter[field_name] = role.optional_fields[field_name]
    frontmatter_text = yaml.safe_dump(frontmatter, sort_keys=False).strip()
    output_lines = "\n".join(f"- {item}" for item in role.output_contract)
    return (
        f"<!-- {GENERATED_FILE_HEADER}\n{role_adapter_comments(role, '')}\n-->\n"
        f"---\n{frontmatter_text}\n---\n\n"
        f"{role.instructions}\n\n"
        f"Load these skills when applicable: {', '.join(role.skills)}.\n\n"
        f"Return:\n\n{output_lines}\n"
    )


def expected_role_outputs(roles: Sequence[RoleDefinition]) -> dict[Path, str]:
    outputs = {ROLE_OUTPUT_PATH: render_role_javascript(roles)}
    for role in roles:
        outputs[CODEX_AGENT_OUTPUT_ROOT / f"{role.filename}{CODEX_AGENT_EXTENSION}"] = render_codex_agent(role)
        outputs[CLAUDE_AGENT_OUTPUT_ROOT / f"{role.filename}{CLAUDE_AGENT_EXTENSION}"] = render_claude_agent(role)
    return outputs


def stale_generated_adapter_paths(expected_paths: set[Path]) -> list[Path]:
    generated_paths: set[Path] = set()
    if CODEX_AGENT_OUTPUT_ROOT.is_dir():
        generated_paths.update(CODEX_AGENT_OUTPUT_ROOT.glob(f"*{CODEX_AGENT_EXTENSION}"))
    if CLAUDE_AGENT_OUTPUT_ROOT.is_dir():
        generated_paths.update(CLAUDE_AGENT_OUTPUT_ROOT.glob(f"*{CLAUDE_AGENT_EXTENSION}"))
    return sorted(generated_paths - expected_paths)


def write_role_outputs(roles: Sequence[RoleDefinition], check: bool) -> list[Path]:
    expected_outputs = expected_role_outputs(roles)
    changed_paths = [
        path
        for path, content in expected_outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]
    stale_paths = stale_generated_adapter_paths(set(expected_outputs))
    if check:
        return sorted(changed_paths + stale_paths)

    for path in stale_paths:
        path.unlink()
    for path in changed_paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected_outputs[path], encoding="utf-8")
    return sorted(changed_paths + stale_paths)


def write_output(check: bool) -> bool:
    rendered = render_javascript(build_payload())
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else None
    if current == rendered:
        return False
    if check:
        return True
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return True


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate skill, role, adapter, and HTML documentation data.")
    parser.add_argument("--check", action="store_true", help="Fail when generated methodology data is stale.")
    args = parser.parse_args(arguments)

    try:
        skill_payload = build_payload()
        changed = write_output(args.check)
        roles = load_role_definitions(set(skill_payload["skills"]))
        changed_role_paths = write_role_outputs(roles, args.check)
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(error, file=sys.stderr)
        return ERROR_EXIT_CODE

    if args.check and (changed or changed_role_paths):
        if changed:
            print(f"stale {OUTPUT_PATH}")
        for path in changed_role_paths:
            print(f"stale {path}")
        return ERROR_EXIT_CODE
    if changed:
        print(f"generated {OUTPUT_PATH}")
    for path in changed_role_paths:
        print(f"generated {path}")
    if not changed and not changed_role_paths:
        print("Methodology documentation data is current.")
    return SUCCESS_EXIT_CODE


if __name__ == "__main__":
    raise SystemExit(main())
